version: '3.4'

services:
  cdvproject:
    image: cdvproject
    build:
      context: vendor/symfony/flex/tests/Fixtures/packageJson/vendor/symfony/new-package/assets
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
